version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DB_TYPE=mariadb+pymysql
      - DB_USER=questionnaire_user
      - DB_PASSWORD=questionnaire_password
      - DB_SERVER=mariadb
      - DB=questionnaire_db
      - SECRET_KEY=your_secret_key_here
      - JWT_SECRET_KEY=your_jwt_secret_key_here
      - DOTENV=true
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - mariadb
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=questionnaire_db
      - MYSQL_USER=questionnaire_user
      - MYSQL_PASSWORD=questionnaire_password
    volumes:
      - mariadb_data:/var/lib/mysql
    # ports:
    #    - "3306:3306"
    networks:
      - app-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
