# .github/workflows/main.yml
name: Main workflow
on:
  push:
    branches:
      - master

jobs:
  tests:
    name: "Codestyle check"
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13t" # Free threaded Python 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install ruff
    - name: Lint with ruff
      run: python -m ruff check
